import { useRef, type KeyboardEvent } from "react";
import AttachFileRoundedIcon from "@mui/icons-material/AttachFileRounded";
import SendRoundedIcon from "@mui/icons-material/SendRounded";
import { Alert, Box, CircularProgress, IconButton, Stack, TextField, Typography } from "@mui/material";
import { AttachmentsPreview } from "./AttachmentsPreview";
import { LocalAttachmentsPreview } from "./LocalAttachmentsPreview";
import type { RequestDetail } from "./types";
import { selectAttachmentFiles } from "../requests/attachments";
interface Props { request: RequestDetail; currentUserId?: string; text: string; files: File[]; sending: boolean; readOnly: boolean; error?: string; onText: (value: string) => void; onFiles: (files: File[]) => void; onError: (message: string) => void; onSend: () => Promise<void> }
export function ManagementCompanyRequestConversation(props: Props) {
  const inputRef = useRef<HTMLInputElement>(null);
  const send = async () => { if (!props.text.trim() || props.sending) return; await props.onSend(); requestAnimationFrame(() => inputRef.current?.focus()); };
  const keyDown = (event: KeyboardEvent<HTMLDivElement>) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void send(); } };
  const original = props.request.attachments.filter(item => !item.messageId);
  return <Stack spacing={2}>{original.length > 0 && <Box><Typography variant="subtitle2" mb={1}>Anexos da solicitação</Typography><AttachmentsPreview items={original} /></Box>}<Stack spacing={1.25} sx={{ maxHeight: 480, overflowY: "auto", p: { xs: 1, sm: 1.5 }, bgcolor: "action.hover", borderRadius: 2 }}>
    {props.request.messages.length === 0 && <Typography color="text.secondary">Ainda não há mensagens.</Typography>}{[...props.request.messages].sort((a,b) => a.createdAt.localeCompare(b.createdAt)).map(message => { const mine = message.authorUserId === props.currentUserId; const meta = message.authorRole.startsWith(`${message.authorName} ·`) ? message.authorRole : [message.authorName, message.authorRole].filter((value, index, all) => value && all.indexOf(value) === index).join(" · "); return <Box key={message.id} alignSelf={mine ? "flex-end" : "flex-start"} maxWidth={{ xs: "92%", sm: "78%" }} sx={{ bgcolor: mine ? "primary.main" : "background.paper", color: mine ? "primary.contrastText" : "text.primary", px: 1.75, py: 1.25, borderRadius: mine ? "16px 16px 4px 16px" : "16px 16px 16px 4px", boxShadow: 1 }}><Typography variant="caption" sx={{ opacity: .78 }}>{meta} · {new Date(message.createdAt).toLocaleString("pt-BR")}</Typography><Typography sx={{ whiteSpace: "pre-wrap", overflowWrap: "anywhere" }}>{message.content}</Typography><Box mt={message.content ? 1 : 0}><AttachmentsPreview items={props.request.attachments.filter(item => item.messageId === message.id)} /></Box></Box>; })}
  </Stack>{!props.readOnly && <Box component="form" onSubmit={event => { event.preventDefault(); void send(); }}>{props.error && <Alert severity="error" sx={{ mb: 1 }}>{props.error}</Alert>}<LocalAttachmentsPreview files={props.files} onRemove={index => props.onFiles(props.files.filter((_, current) => current !== index))} /><Box display="flex" alignItems="flex-end" gap={.75} mt={1} sx={{ border: 1, borderColor: "divider", borderRadius: 3, p: .75, bgcolor: "background.paper" }}><IconButton component="label" aria-label="Anexar arquivos" disabled={props.sending}><AttachFileRoundedIcon /><input hidden multiple type="file" onChange={event => { const result = selectAttachmentFiles(props.files, Array.from(event.target.files ?? [])); props.onFiles(result.files); if (result.error) props.onError(result.error); event.target.value = ""; }} /></IconButton><TextField inputRef={inputRef} fullWidth multiline maxRows={6} variant="standard" placeholder="Escreva uma mensagem..." value={props.text} onChange={event => props.onText(event.target.value)} onKeyDown={keyDown} disabled={props.sending} InputProps={{ disableUnderline: true }} /><IconButton type="submit" color="primary" aria-label="Enviar mensagem" disabled={props.sending || !props.text.trim()}>{props.sending ? <CircularProgress size={22} /> : <SendRoundedIcon />}</IconButton></Box></Box>}</Stack>;
}
