import { Box, Card, CardContent, Stack, Typography } from "@mui/material";
import { AttachmentsPreview } from "./AttachmentsPreview";
import { date, money } from "./presentation";
import { hasAttachmentPurpose, type RequestDetail } from "./types";
export function RequestInformationCards({ request, showRequester = false }: { request: RequestDetail; showRequester?: boolean }) {
  const boleto = request.attachments.filter(x => hasAttachmentPurpose(x, "PaymentBoleto"));
  return <Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", md: showRequester ? "minmax(0, 1fr) minmax(0, 1.35fr)" : "1fr" }, gap: 2 }}>
    {showRequester && <Card variant="outlined"><CardContent><Typography variant="h2" mb={1}>Informações do solicitante</Typography><Typography fontWeight={700}>{request.requester.role === "Manager" ? "Síndico" : request.requester.role === "SubManager" ? "Subsíndico" : "Solicitante"}: {request.requester.fullName}</Typography><Typography>{request.condominium?.name ?? request.condominiumName}</Typography></CardContent></Card>}
    <Card variant="outlined"><CardContent><Typography variant="h2" mb={1}>Dados da solicitação</Typography>{request.fine && <Stack><Typography><b>Unidade:</b> {request.fine.block ? `${request.fine.block} / ` : ""}{request.fine.unit ?? request.fine.unitId}</Typography><Typography><b>Natureza:</b> {request.fine.nature}</Typography><Typography><b>Descrição:</b> {request.fine.description}</Typography><Typography><b>Data:</b> {date(request.fine.occurrenceDate)}</Typography><Typography><b>Valor:</b> {request.fine.valueNotDefined ? "Valor ainda não definido" : money(request.fine.value!)}</Typography></Stack>}{request.payment && <Stack spacing={1.25}><Typography><b>Natureza:</b> {request.payment.nature}</Typography><Typography><b>Valor:</b> {money(request.payment.value)}</Typography><Typography><b>Data:</b> {date(request.payment.eventDate)}</Typography><Typography><b>Vencimento:</b> {request.payment.dueDate ? date(request.payment.dueDate) : "—"}</Typography>{request.payment.notes && <Typography><b>Observações:</b> {request.payment.notes}</Typography>}</Stack>}{request.question && <Typography><b>Tema:</b> {request.question.theme}</Typography>}</CardContent></Card>
    {request.payment && <Card variant="outlined"><CardContent><Typography variant="h2" mb={1}>Forma de pagamento</Typography>{request.payment.isReimbursement ? <Stack><Typography><b>Modalidade:</b> Reembolso</Typography><Typography><b>Beneficiário:</b> {request.payment.beneficiaryName}</Typography><Typography><b>PIX:</b> {request.payment.pixKeyType} · {request.payment.pixKey}</Typography></Stack> : <Stack><Typography><b>Modalidade:</b> Terceiro</Typography><Typography><b>Identificação:</b> {request.payment.thirdPartyIdentification}</Typography><Typography><b>Forma:</b> {request.payment.thirdPartyForm === "Pix" ? "PIX" : request.payment.thirdPartyForm === "Boleto" ? "Boleto" : "Conta para depósito"}</Typography>{request.payment.thirdPartyForm === "Pix" && <Typography><b>Chave PIX:</b> {request.payment.thirdPartyPixKey}</Typography>}{request.payment.thirdPartyForm === "Boleto" && <AttachmentsPreview items={boleto} />}{request.payment.thirdPartyForm === "DepositAccount" && <><Typography><b>Banco:</b> {request.payment.thirdPartyBank}</Typography><Typography><b>Agência:</b> {request.payment.thirdPartyAgency}</Typography><Typography><b>Conta:</b> {request.payment.thirdPartyAccount}</Typography></>}</Stack>}</CardContent></Card>}
  </Box>;
}
