import { useEffect, useState } from 'react'
import { Alert, Autocomplete, Box, Button, Card, CardContent, Checkbox, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, MenuItem, Stack, TextField, Typography } from '@mui/material'
import { PageContainer } from '../components/PageContainer'
import { useManagementContext } from '../management/ManagementContext'
import { hasWhatsAppPhone, OpenProviderWhatsAppButton } from '../requests/components/ProviderWhatsAppDialog'
import { createServiceProvider, listServiceProviders, updateServiceProvider, type PixKeyType, type ServiceProvider, type ServiceProviderInput } from './api'

const blank: ServiceProviderInput = { name:'', companyName:'', specialties:[], phone:'', email:'', pixKey:'', pixKeyType:null, notes:'', isMine:true, condominiumIds:[], isActive:true }
const errorMessage=(value:unknown)=>(value as {response?:{data?:{error?:string;title?:string}}})?.response?.data?.error??(value as {response?:{data?:{title?:string}}})?.response?.data?.title??'Não foi possível salvar o prestador.'

export function ServiceProvidersPage() {
  const { condominiums, activeCondominiumId }=useManagementContext(); const [items,setItems]=useState<ServiceProvider[]>([]),[search,setSearch]=useState(''),[status,setStatus]=useState('active'),[availability,setAvailability]=useState(''),[editing,setEditing]=useState<ServiceProvider|null>(null),[form,setForm]=useState(blank),[dialog,setDialog]=useState(false),[error,setError]=useState('')
  const load=()=>listServiceProviders({search:search||undefined,status,availability:availability||undefined}).then(setItems).catch(()=>setError('Não foi possível carregar prestadores.'))
  // The request intentionally reloads when the administrative context changes.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{void load()},[search,status,availability,activeCondominiumId])
  const open=(item?:ServiceProvider)=>{setEditing(item??null);setDialog(true);setError('');setForm(item?{name:item.name,companyName:item.companyName??'',specialties:item.specialties?.length?item.specialties:[item.specialty],phone:item.phone,email:item.email??'',pixKey:item.pixKey??'',pixKeyType:item.pixKeyType,notes:item.notes??'',isMine:item.isMine,condominiumIds:item.condominiums.map(x=>x.condominiumId),isActive:item.isActive}:{...blank,condominiumIds:activeCondominiumId?[activeCondominiumId]:[]})}
  const save=async()=>{try{const result=editing?await updateServiceProvider(editing.id,form):await createServiceProvider(form);setItems(old=>editing?old.map(x=>x.id===result.id?result:x):[result,...old]);setDialog(false)}catch(e){setError(errorMessage(e))}}
  const specialties=(values:string[])=>setForm({...form,specialties:Array.from(new Map(values.map(x=>[x.trim().toLowerCase(),x.trim()])).values()).filter(Boolean)})
  return <PageContainer maxWidth={1440}>
    <Stack gap={2}>
      <Box display="flex" justifyContent="space-between" gap={2} flexWrap="wrap"><Box><Typography variant="h1">Prestadores</Typography><Typography color="text.secondary">Meus prestadores e prestadores dos condomínios administrados.</Typography></Box><Button variant="contained" onClick={()=>open()}>Novo prestador</Button></Box>
      {error&&<Alert severity="error">{error}</Alert>}
      <Stack direction={{xs:'column',sm:'row'}} gap={1.5}><TextField label="Buscar" value={search} onChange={e=>setSearch(e.target.value)} fullWidth/><TextField select label="Status" value={status} onChange={e=>setStatus(e.target.value)}><MenuItem value="active">Ativos</MenuItem><MenuItem value="inactive">Inativos</MenuItem><MenuItem value="">Todos</MenuItem></TextField><TextField select label="Disponibilidade" value={availability} onChange={e=>setAvailability(e.target.value)}><MenuItem value="">Todos</MenuItem><MenuItem value="mine">Meus</MenuItem><MenuItem value="condominium">Do condomínio</MenuItem></TextField></Stack>
      {items.length===0?<Alert severity="info">Nenhum prestador encontrado.</Alert>:items.map(item=><Card key={item.id} variant="outlined"><CardContent><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2}><Box><Typography fontWeight={800}>{item.name}</Typography>{item.companyName&&<Typography color="text.secondary">{item.companyName}</Typography>}<Stack direction="row" flexWrap="wrap" gap={.75} mt={1}>{(item.specialties?.length?item.specialties:[item.specialty]).map(tag=><Chip key={tag} size="small" label={tag}/>)}{item.isMine&&<Chip size="small" label="Meu prestador"/>}{item.condominiums.map(c=><Chip size="small" key={c.condominiumId} label={c.name}/>)}</Stack></Box><Stack direction="row" gap={1} alignSelf={{xs:'flex-start',sm:'center'}}><Button onClick={()=>open(item)}>Editar</Button>{hasWhatsAppPhone(item.phone)&&<OpenProviderWhatsAppButton phone={item.phone}/>}</Stack></Stack></CardContent></Card>)}
    </Stack>
    <Dialog open={dialog} onClose={()=>setDialog(false)} fullWidth maxWidth="sm"><DialogTitle>{editing?'Editar prestador':'Novo prestador'}</DialogTitle><DialogContent dividers><Stack gap={2}><Stack direction={{xs:'column',sm:'row'}} gap={1}><TextField label="Nome" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required fullWidth/><TextField label="Empresa" value={form.companyName} onChange={e=>setForm({...form,companyName:e.target.value})} fullWidth/></Stack><Autocomplete multiple freeSolo options={[]} value={form.specialties} onChange={(_,values)=>specialties(values)} renderTags={(value,getTagProps)=>value.map((option,index)=><Chip {...getTagProps({index})} key={option.toLowerCase()} label={option}/>)} renderInput={params=><TextField {...params} label="Especialidades" placeholder="Digite e pressione Enter" required/>}/><TextField label="Telefone / WhatsApp" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} required/><Stack direction={{xs:'column',sm:'row'}} gap={1}><TextField label="E-mail" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} fullWidth/><TextField select label="Tipo PIX" value={form.pixKeyType??''} onChange={e=>setForm({...form,pixKeyType:(e.target.value||null) as PixKeyType|null})}><MenuItem value="">Sem PIX</MenuItem>{(['Cpf','Cnpj','Email','Phone','Random'] as PixKeyType[]).map(x=><MenuItem value={x} key={x}>{x}</MenuItem>)}</TextField></Stack>{form.pixKeyType&&<TextField label="Chave PIX" value={form.pixKey} onChange={e=>setForm({...form,pixKey:e.target.value})}/>}<TextField label="Observações" multiline minRows={2} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><Box><Typography variant="h3">Disponibilidade</Typography><FormControlLabel control={<Checkbox checked={form.isMine} onChange={e=>setForm({...form,isMine:e.target.checked})}/>} label="Meu prestador — disponível na minha agenda"/><FormControlLabel control={<Checkbox checked={form.condominiumIds.length>0} onChange={e=>setForm({...form,condominiumIds:e.target.checked?(activeCondominiumId?[activeCondominiumId]:[]):[]})}/>} label="Prestador do condomínio — disponível para a gestão"/>{form.condominiumIds.length>0&&<TextField select label="Condomínios" value={form.condominiumIds} SelectProps={{multiple:true}} onChange={e=>setForm({...form,condominiumIds:typeof e.target.value==='string'?e.target.value.split(','):e.target.value as string[]})} fullWidth>{condominiums.map(c=><MenuItem key={c.id} value={c.id}>{c.name}</MenuItem>)}</TextField>}</Box></Stack></DialogContent><DialogActions><Button onClick={()=>setDialog(false)}>Cancelar</Button><Button variant="contained" onClick={()=>void save()}>Salvar</Button></DialogActions></Dialog>
  </PageContainer>
}
