import { useEffect, useState } from 'react'
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, TextField, Typography } from '@mui/material'
import { PageContainer } from '../components/PageContainer'
import { useManagementContext } from '../management/ManagementContext'
import { hasWhatsAppPhone, OpenProviderWhatsAppButton } from '../requests/components/ProviderWhatsAppDialog'
import { createServiceProvider, listServiceProviders, updateServiceProvider, type PixKeyType, type ServiceProvider, type ServiceProviderInput } from './api'

const blank: ServiceProviderInput = { name: '', companyName: '', specialty: '', contactName: '', phone: '', email: '', pixKey: '', pixKeyType: null, notes: '', isMine: true, condominiumIds: [], isActive: true }

export function ServiceProvidersPage() {
  const { condominiums, activeCondominiumId } = useManagementContext()
  const [items, setItems] = useState<ServiceProvider[]>([]), [search, setSearch] = useState(''), [status, setStatus] = useState('active'), [availability, setAvailability] = useState(''), [editing, setEditing] = useState<ServiceProvider | null>(null), [form, setForm] = useState(blank), [dialog, setDialog] = useState(false), [error, setError] = useState('')
  const load = () => listServiceProviders({ search: search || undefined, status, availability: availability || undefined }).then(setItems).catch(() => setError('Não foi possível carregar prestadores.'))
  useEffect(() => { void load() }, [search, status, availability, activeCondominiumId])
  const open = (item?: ServiceProvider) => { setEditing(item ?? null); setDialog(true); setForm(item ? { name: item.name, companyName: item.companyName ?? '', specialty: item.specialty, contactName: item.contactName ?? '', phone: item.phone, email: item.email ?? '', pixKey: item.pixKey ?? '', pixKeyType: item.pixKeyType, notes: item.notes ?? '', isMine: item.isMine, condominiumIds: item.condominiums.map(x => x.condominiumId), isActive: item.isActive } : { ...blank, condominiumIds: activeCondominiumId ? [activeCondominiumId] : [] }) }
  const close = () => { setDialog(false); setEditing(null) }
  const save = async () => { try { const result = editing ? await updateServiceProvider(editing.id, form) : await createServiceProvider(form); setItems(current => editing ? current.map(x => x.id === result.id ? result : x) : [result, ...current]); close() } catch { setError('Não foi possível salvar o prestador.') } }

  return <PageContainer maxWidth={1440}>
    <Stack gap={2}>
      <Box display="flex" justifyContent="space-between" gap={2} flexWrap="wrap"><Box><Typography variant="h1">Prestadores</Typography><Typography color="text.secondary">Meus prestadores e prestadores dos condomínios administrados.</Typography></Box><Button variant="contained" onClick={() => open()}>Novo prestador</Button></Box>
      {error && <Alert severity="error">{error}</Alert>}
      <Stack direction={{ xs: 'column', sm: 'row' }} gap={1.5}><TextField label="Buscar" value={search} onChange={e => setSearch(e.target.value)} fullWidth /><TextField select label="Status" value={status} onChange={e => setStatus(e.target.value)} sx={{ minWidth: 150 }}><MenuItem value="active">Ativos</MenuItem><MenuItem value="inactive">Inativos</MenuItem><MenuItem value="">Todos</MenuItem></TextField><TextField select label="Disponibilidade" value={availability} onChange={e => setAvailability(e.target.value)} sx={{ minWidth: 180 }}><MenuItem value="">Todos</MenuItem><MenuItem value="mine">Meus</MenuItem><MenuItem value="condominium">Do condomínio</MenuItem></TextField></Stack>
      {items.length === 0 ? <Alert severity="info">Nenhum prestador encontrado.</Alert> : items.map(item => <Card key={item.id} variant="outlined"><CardContent><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" gap={2}><Box><Typography fontWeight={800}>{item.name}</Typography><Typography color="text.secondary">{item.specialty}{item.companyName ? ` · ${item.companyName}` : ''}</Typography><Typography>{item.phone}{item.contactName ? ` · ${item.contactName}` : ''}</Typography><Stack direction="row" flexWrap="wrap" gap={.75} mt={1}>{item.isMine && <Chip size="small" label="Meu prestador" />}{item.condominiums.map(c => <Chip size="small" key={c.condominiumId} label={c.name} />)}{!item.isActive && <Chip size="small" label="Inativo" />}</Stack></Box><Stack direction="row" gap={1} alignSelf={{ xs: 'flex-start', sm: 'center' }}><Button onClick={() => open(item)}>Editar</Button>{hasWhatsAppPhone(item.phone) && <OpenProviderWhatsAppButton phone={item.phone} />}</Stack></Stack></CardContent></Card>)}
    </Stack>
    <Dialog open={dialog} onClose={close} fullWidth maxWidth="sm"><DialogTitle>{editing ? 'Editar prestador' : 'Novo prestador'}</DialogTitle><DialogContent><Stack gap={1.5} mt={1}><TextField label="Nome" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} required /><TextField label="Empresa" value={form.companyName} onChange={e => setForm({ ...form, companyName: e.target.value })} /><TextField label="Especialidade / tipo de serviço" value={form.specialty} onChange={e => setForm({ ...form, specialty: e.target.value })} required /><TextField label="Contato" value={form.contactName} onChange={e => setForm({ ...form, contactName: e.target.value })} /><TextField label="Telefone/WhatsApp" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} required /><TextField label="E-mail" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /><Stack direction="row" gap={1}><TextField label="Chave PIX" value={form.pixKey} onChange={e => setForm({ ...form, pixKey: e.target.value })} fullWidth /><TextField select label="Tipo PIX" value={form.pixKeyType ?? ''} onChange={e => setForm({ ...form, pixKeyType: (e.target.value || null) as PixKeyType | null })} sx={{ minWidth: 140 }}><MenuItem value="">Nenhum</MenuItem>{(['Cpf', 'Cnpj', 'Email', 'Phone', 'Random'] as PixKeyType[]).map(x => <MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField></Stack><TextField label="Observações" multiline minRows={3} value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /><Stack direction="row" gap={1}><Button variant={form.isMine ? 'contained' : 'outlined'} onClick={() => setForm({ ...form, isMine: !form.isMine })}>Meu prestador</Button><TextField select label="Condomínios" value={form.condominiumIds} SelectProps={{ multiple: true }} onChange={e => setForm({ ...form, condominiumIds: typeof e.target.value === 'string' ? e.target.value.split(',') : e.target.value as string[] })} fullWidth>{condominiums.map(c => <MenuItem key={c.id} value={c.id}>{c.name}</MenuItem>)}</TextField></Stack></Stack></DialogContent><DialogActions><Button onClick={close}>Cancelar</Button><Button variant="contained" onClick={() => void save()}>Salvar</Button></DialogActions></Dialog>
  </PageContainer>
}
