// <auto-generated />
using CondoLink.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CondoLink.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260903090000_RestoreGlobalSubManagerUniqueness")]
partial class RestoreGlobalSubManagerUniqueness
{
}
