import { useMemo, useState } from "react";
import { Button, Chip, Stack, Typography } from "@mui/material";
import type { AssistantOperationalReference, AssistantSource } from "./api";

interface SourceGroup { documentId: string; documentName: string; pages: number[]; documentExists: boolean; documentCurrentlyActive: boolean }
const technicalName = /^(?:s3[-_/]|[0-9a-f]{16,}(?:\.[a-z0-9]+)?$|[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}(?:\.[a-z0-9]+)?$)/i;
function friendlyName(source: AssistantSource) { return technicalName.test(source.documentName) && source.originalFileName ? source.originalFileName : source.documentName; }
function compactPages(pages: number[]) { const sorted = [...new Set(pages)].sort((a, b) => a - b); const ranges: string[] = []; for (let index = 0; index < sorted.length;) { let end = index; while (end + 1 < sorted.length && sorted[end + 1] === sorted[end] + 1) end++; ranges.push(index === end ? `${sorted[index]}` : `${sorted[index]}–${sorted[end]}`); index = end + 1; } return ranges.join(", "); }
function groupSources(sources: AssistantSource[]): SourceGroup[] { const groups = new Map<string, SourceGroup>(); for (const source of sources) { const current = groups.get(source.documentId); if (current) { if (source.pageNumber != null && !current.pages.includes(source.pageNumber)) current.pages.push(source.pageNumber); current.documentExists ||= source.documentExists !== false; current.documentCurrentlyActive ||= source.documentCurrentlyActive !== false; } else groups.set(source.documentId, { documentId: source.documentId, documentName: friendlyName(source), pages: source.pageNumber == null ? [] : [source.pageNumber], documentExists: source.documentExists !== false, documentCurrentlyActive: source.documentCurrentlyActive !== false }); } return [...groups.values()]; }

export function AssistantSources({ sources, operationalReferences = [], onDownload }: { sources: AssistantSource[]; operationalReferences?: AssistantOperationalReference[]; onDownload: (documentId: string, documentName: string) => Promise<void> }) {
  const [expanded, setExpanded] = useState(false);
  const groups = useMemo(() => groupSources(sources), [sources]);
  const visible = expanded ? groups : groups.slice(0, 3);
  const labelFor = (group: SourceGroup) => { const pages = compactPages(group.pages); const pageLabel = pages ? ` · ${group.pages.length === 1 ? "pág." : "págs."} ${pages}` : ""; const status = !group.documentExists ? " · documento removido" : !group.documentCurrentlyActive ? " · documento atualmente inativo" : ""; return `${group.documentName}${pageLabel}${status}`; };
  return <Stack mt={1} gap={.5} maxWidth="100%">
    {operationalReferences.length > 0 && <><Typography variant="caption" fontWeight={800}>Relacionado</Typography><Stack direction="row" gap={.5} flexWrap="wrap" minWidth={0}>{operationalReferences.map(reference => reference.href ? <Chip key={`${reference.type}-${reference.id}`} component="a" href={reference.href} clickable label={`${reference.label} →`} /> : <Chip key={`${reference.type}-${reference.id}`} label={reference.label} />)}</Stack></>}
    {groups.length > 0 && <><Typography variant="caption" fontWeight={800} mt={operationalReferences.length > 0 ? 1 : 0}>Fontes</Typography><Stack direction="row" gap={.5} flexWrap="wrap" minWidth={0}>{visible.map(group => group.documentExists ? <Button key={group.documentId} size="small" variant="outlined" onClick={() => void onDownload(group.documentId, group.documentName)} sx={{ textTransform: "none", maxWidth: { xs: "100%", sm: 440 }, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{labelFor(group)}</Button> : <Typography key={group.documentId} variant="caption" color="text.secondary" sx={{ px: 1, py: .75 }}>{labelFor(group)}</Typography>)}{!expanded && groups.length > 3 && <Button size="small" onClick={() => setExpanded(true)}>+ {groups.length - 3} fontes</Button>}{expanded && groups.length > 3 && <Button size="small" onClick={() => setExpanded(false)}>Mostrar menos</Button>}</Stack></>}
  </Stack>;
}
