import { useEffect, useMemo, useState } from 'react'
import DeleteOutlineRoundedIcon from '@mui/icons-material/DeleteOutlineRounded'
import { Alert, Button, Card, CardContent, Checkbox, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, IconButton, MenuItem, Stack, TextField, Typography } from '@mui/material'
import { PageContainer } from '../components/PageContainer'
import { useManagementContext } from '../management/ManagementContext'
import { deleteDocument, deleteDocuments, downloadDocument, DOCUMENT_FILE_TOO_LARGE_MESSAGE, getDocumentUploadError, listDocuments, MAXIMUM_DOCUMENT_FILE_BYTES, MAXIMUM_DOCUMENT_FILE_MEGABYTES, reprocessDocument, setDocumentActive, setDocumentsActive, uploadDocument, type AssistantDocument } from '../assistant/api'
import { documentStatusLabels, documentTypeLabel, documentTypes, documentTypeLabels, documentVisualStatus, type DocumentType } from '../assistant/documentPresentation'

type UploadStatus='Aguardando'|'Enviando'|'Processando'|'Pronto'|'Falhou'|'Não suportado'
interface UploadItem { id:string; file:File; name:string; type:DocumentType; date:string; status:UploadStatus; error?:string }
const batchLimit=20
const withoutExtension=(name:string)=>name.replace(/\.[^.]+$/,'')
async function limited<T>(items:T[], concurrency:number, work:(item:T)=>Promise<void>) { let cursor=0; await Promise.all(Array.from({length:Math.min(concurrency,items.length)},async()=>{ while(cursor<items.length){const item=items[cursor++];await work(item)} })) }

export function CondominiumDocumentsPage(){
 const {activeCondominiumId}=useManagementContext(); const [documents,setDocuments]=useState<AssistantDocument[]>([]); const [queue,setQueue]=useState<UploadItem[]>([]); const [allType,setAllType]=useState<DocumentType>('Other'); const [error,setError]=useState(''); const [deleting,setDeleting]=useState<AssistantDocument|null>(null); const [search,setSearch]=useState(''); const [filter,setFilter]=useState('All'); const [activeFilter,setActiveFilter]=useState('All'); const [selected,setSelected]=useState<string[]>([]); const [bulkAction,setBulkAction]=useState<'activate'|'deactivate'|'delete'|null>(null); const [uploading,setUploading]=useState(false); const [summary,setSummary]=useState('')
 const load=async()=>{if(activeCondominiumId)setDocuments(await listDocuments(activeCondominiumId))}; useEffect(()=>{void load()},[activeCondominiumId])
 const selectFiles=(files:File[])=>{setError('');const available=Math.max(0,batchLimit-queue.length);if(files.length>available)setError(`Selecione no máximo ${batchLimit} arquivos por lote.`);const added=files.slice(0,available).map((file,index):UploadItem=>({id:`${Date.now()}-${index}-${file.name}`,file,name:withoutExtension(file.name),type:'Other',date:'',status:file.size>MAXIMUM_DOCUMENT_FILE_BYTES?'Falhou':documentTypes.includes((PathExtension(file.name) as never))?'Aguardando':'Não suportado',error:file.size>MAXIMUM_DOCUMENT_FILE_BYTES?DOCUMENT_FILE_TOO_LARGE_MESSAGE:undefined}));setQueue(current=>[...current,...added])}
 const update=(id:string,change:Partial<UploadItem>)=>setQueue(items=>items.map(item=>item.id===id?{...item,...change}:item))
 const upload=async()=>{if(!activeCondominiumId)return;setUploading(true);setSummary('');const pending=queue.filter(x=>x.status==='Aguardando'||x.status==='Falhou'&&x.file.size<=MAXIMUM_DOCUMENT_FILE_BYTES);await limited(pending,3,async item=>{update(item.id,{status:'Enviando',error:undefined});const form=new FormData();form.append('file',item.file);form.append('name',item.name.trim()||withoutExtension(item.file.name));form.append('documentType',item.type);if(item.date)form.append('documentDate',item.date);try{update(item.id,{status:'Processando'});const result=await uploadDocument(activeCondominiumId,form) as {processingStatus?:string;processingError?:string};update(item.id,{status:result.processingStatus==='Unsupported'?'Não suportado':result.processingStatus==='Failed'?'Falhou':'Pronto',error:result.processingError})}catch(e){update(item.id,{status:'Falhou',error:getDocumentUploadError(e)})}});setUploading(false);await load();setQueue(current=>{const sent=current.filter(x=>x.status!=='Aguardando').length;const ready=current.filter(x=>x.status==='Pronto').length;const unsupported=current.filter(x=>x.status==='Não suportado').length;const failed=current.filter(x=>x.status==='Falhou').length;setSummary(`${sent} documentos enviados · ${ready} processados · ${unsupported} não suportados · ${failed} falharam`);return current})}
 const visible=useMemo(()=>documents.filter(d=>(filter==='All'||d.documentType===filter)&&(activeFilter==='All'||(activeFilter==='Active')===d.isActive)&&`${d.name} ${d.documentType} ${d.documentDate??''}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR'))),[documents,filter,activeFilter,search])
 const confirmDelete=async()=>{if(!activeCondominiumId||!deleting)return;try{await deleteDocument(activeCondominiumId,deleting.id);setDocuments(x=>x.filter(d=>d.id!==deleting.id));setDeleting(null)}catch{setError('Não foi possível excluir o documento. Tente novamente.')}}
 const runBulk=async()=>{if(!activeCondominiumId||!bulkAction)return;setError('');try{const result=bulkAction==='delete'?await deleteDocuments(activeCondominiumId,selected):await setDocumentsActive(activeCondominiumId,selected,bulkAction==='activate');setSummary(`${result.succeeded} concluído${result.succeeded===1?'':'s'}${result.failed.length?` · ${result.failed.length} não puderam ser processados: ${result.failed.map(x=>x.reason).join('; ')}`:''}`);setSelected([]);setBulkAction(null);await load()}catch{setError('Não foi possível concluir a ação em massa. Tente novamente.')}}
 const reprocessSelected=async()=>{if(!activeCondominiumId)return;const targets=documents.filter(x=>selected.includes(x.id)&&(x.needsKnowledgeUpdate||x.needsReindexing||x.processingStatus==='Failed'||x.processingStatus==='Unsupported'));await limited(targets,3,async x=>{try{await reprocessDocument(activeCondominiumId,x.id)}catch{/* partial failures appear after reload */}});setSummary(`${targets.length} documento${targets.length===1?'':'s'} reprocessado${targets.length===1?'':'s'}.`);setSelected([]);await load()}
 return <PageContainer><Stack gap={2}><Typography variant="h1">Documentos</Typography>{error&&<Alert severity="error">{error}</Alert>}{summary&&<Alert severity="info">{summary}</Alert>}
 <Card onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();selectFiles(Array.from(e.dataTransfer.files))}}><CardContent><Stack gap={2}><Stack direction={{xs:'column',md:'row'}} gap={2}><Button component="label" variant="outlined">Selecionar ou arrastar PDF, DOCX ou TXT<input hidden multiple type="file" accept=".pdf,.docx,.txt" onChange={e=>{selectFiles(Array.from(e.target.files??[]));e.target.value='' }}/></Button><TextField select label="Tipo para todos" value={allType} onChange={e=>setAllType(e.target.value as DocumentType)} sx={{minWidth:220}}>{documentTypes.map(t=><MenuItem key={t} value={t}>{documentTypeLabels[t]}</MenuItem>)}</TextField><Button disabled={!queue.length} onClick={()=>setQueue(items=>items.map(x=>({...x,type:allType})))}>Aplicar aos arquivos</Button><Button variant="contained" disabled={uploading||!queue.some(x=>x.status==='Aguardando'||x.status==='Falhou'&&x.file.size<=MAXIMUM_DOCUMENT_FILE_BYTES)} onClick={()=>void upload()}>Enviar documentos</Button></Stack><Typography variant="caption">PDF, DOCX ou TXT · máximo {MAXIMUM_DOCUMENT_FILE_MEGABYTES} MB por arquivo · até {batchLimit} arquivos · 3 uploads simultâneos</Typography>
 {queue.map(item=><Card variant="outlined" key={item.id}><CardContent><Stack direction={{xs:'column',md:'row'}} gap={1} alignItems={{md:'center'}}><Typography sx={{minWidth:180}}>{item.file.name}</Typography><TextField size="small" label={`Nome ${item.file.name}`} value={item.name} onChange={e=>update(item.id,{name:e.target.value})}/><TextField size="small" select label={`Tipo ${item.file.name}`} value={item.type} onChange={e=>update(item.id,{type:e.target.value as DocumentType})} sx={{minWidth:180}}>{documentTypes.map(t=><MenuItem key={t} value={t}>{documentTypeLabels[t]}</MenuItem>)}</TextField><TextField size="small" type="date" label={`Data do documento ${item.file.name}`} slotProps={{inputLabel:{shrink:true}}} value={item.date} onChange={e=>update(item.id,{date:e.target.value})}/><Chip label={item.status} color={item.status==='Pronto'?'success':item.status==='Falhou'||item.status==='Não suportado'?'error':'default'}/><Button aria-label={`Remover ${item.file.name}`} onClick={()=>setQueue(x=>x.filter(y=>y.id!==item.id))}>Remover</Button></Stack>{item.error&&<Alert severity="warning" sx={{mt:1}}>{item.error}</Alert>}</CardContent></Card>)}</Stack></CardContent></Card>
 <Stack direction={{xs:'column',sm:'row'}} gap={2}><TextField fullWidth label="Buscar documentos" value={search} onChange={e=>setSearch(e.target.value)}/><TextField select label="Filtrar por tipo" value={filter} onChange={e=>setFilter(e.target.value)} sx={{minWidth:220}}><MenuItem value="All">Todos</MenuItem>{documentTypes.map(t=><MenuItem key={t} value={t}>{documentTypeLabels[t]}</MenuItem>)}</TextField><TextField select label="Filtrar por atividade" value={activeFilter} onChange={e=>setActiveFilter(e.target.value)} sx={{minWidth:190}}><MenuItem value="All">Ativos e inativos</MenuItem><MenuItem value="Active">Ativos</MenuItem><MenuItem value="Inactive">Inativos</MenuItem></TextField></Stack>
 <Stack direction={{xs:'column',sm:'row'}} gap={1} alignItems={{sm:'center'}}><FormControlLabel control={<Checkbox checked={visible.length>0&&visible.every(x=>selected.includes(x.id))} indeterminate={visible.some(x=>selected.includes(x.id))&&!visible.every(x=>selected.includes(x.id))} onChange={(_,checked)=>setSelected(current=>checked?Array.from(new Set([...current,...visible.map(x=>x.id)])):current.filter(id=>!visible.some(x=>x.id===id)))}/>} label="Selecionar todos"/>{selected.length>0&&<><Typography>{selected.length} documento{selected.length===1?'':'s'} selecionado{selected.length===1?'':'s'}</Typography><Button onClick={()=>setBulkAction('deactivate')}>Inativar</Button><Button disabled={!documents.some(x=>selected.includes(x.id)&&!x.isActive&&x.processingStatus==='Ready')} onClick={()=>setBulkAction('activate')}>Ativar</Button><Button onClick={()=>void reprocessSelected()}>Reprocessar selecionados</Button><Button color="error" onClick={()=>setBulkAction('delete')}>Excluir</Button></>}</Stack>
 {visible.map(document=>{const status=documentVisualStatus(document);return <Card key={document.id}><CardContent><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2}><Stack direction="row" alignItems="flex-start"><Checkbox aria-label={`Selecionar ${document.name}`} checked={selected.includes(document.id)} onChange={(_,checked)=>setSelected(x=>checked?[...x,document.id]:x.filter(id=>id!==document.id))}/><div><Typography fontWeight={800}>{document.name}</Typography><Typography color="text.secondary">{documentTypeLabel(document.documentType)} · {document.documentDate??'Sem data'} · {document.originalFileName} · versão {document.version}</Typography>{document.needsKnowledgeUpdate&&<Alert severity="info" sx={{mt:1}}>Atualização de conhecimento necessária</Alert>}{document.processingError&&<Alert severity="warning" sx={{mt:1}}>{document.processingError}</Alert>}</div></Stack><Stack direction="row" gap={1} alignItems="center" flexWrap="wrap"><Chip label={documentStatusLabels[status]??status} color={status==='Ready'?'success':status==='Failed'||status==='Unsupported'?'error':status==='ReindexRequired'?'warning':'default'}/>{(document.needsKnowledgeUpdate||document.needsReindexing||document.processingStatus==='Failed'||document.processingStatus==='Unsupported')&&<Button onClick={async()=>{await reprocessDocument(activeCondominiumId!,document.id);await load()}}>Reprocessar</Button>}<Button disabled={!document.isActive&&document.processingStatus!=='Ready'} onClick={async()=>{await setDocumentActive(activeCondominiumId!,document.id,!document.isActive);await load()}}>{document.isActive?'Inativar':'Ativar'}</Button><Button onClick={async()=>{try{await downloadDocument(activeCondominiumId!,document.id,document.originalFileName)}catch{setError('Não foi possível baixar o documento. Tente novamente.')}}}>Baixar</Button><IconButton aria-label={`Excluir ${document.name}`} onClick={()=>setDeleting(document)}><DeleteOutlineRoundedIcon/></IconButton></Stack></Stack></CardContent></Card>})}
 <Dialog open={Boolean(deleting)} onClose={()=>setDeleting(null)}><DialogTitle>Excluir documento?</DialogTitle><DialogContent>“{deleting?.name}” será removido definitivamente. Esta ação não pode ser desfeita.</DialogContent><DialogActions><Button onClick={()=>setDeleting(null)}>Cancelar</Button><Button color="error" onClick={()=>void confirmDelete()}>Excluir</Button></DialogActions></Dialog>
 <Dialog open={bulkAction!==null} onClose={()=>setBulkAction(null)}><DialogTitle>{bulkAction==='delete'?`Excluir definitivamente ${selected.length} documentos?`:bulkAction==='activate'?`Ativar ${selected.length} documentos?`:`Inativar ${selected.length} documentos?`}</DialogTitle><DialogContent>{bulkAction==='delete'?'Os arquivos e índices serão removidos. Fontes já utilizadas em conversas históricas continuarão identificadas como documentos removidos.':'A alteração terá efeito imediato nas novas consultas do Assistente.'}</DialogContent><DialogActions><Button onClick={()=>setBulkAction(null)}>Cancelar</Button><Button color={bulkAction==='delete'?'error':'primary'} onClick={()=>void runBulk()}>Confirmar</Button></DialogActions></Dialog>
 </Stack></PageContainer>
}
function PathExtension(name:string){const ext=name.split('.').pop()?.toLowerCase();return ext==='pdf'||ext==='docx'||ext==='txt'?'Other':'Unsupported'}
