import { useEffect, useState } from "react";
import { Alert, Button, InputAdornment, MenuItem, Stack, TextField, Typography } from "@mui/material";
import { useNavigate, useParams } from "react-router-dom";
import { PageContainer } from "../components/PageContainer";
import { getRequest, updateRequest } from "../managementCompanyRequests/api";
import { AttachmentsPreview } from "../managementCompanyRequests/AttachmentsPreview";
import { moneyInput, parseMoneyInput } from "../managementCompanyRequests/presentation";
import type { RequestDetail } from "../managementCompanyRequests/types";

type FormState = Record<string, string>;
const unitLabel = (fine: RequestDetail["fine"]) => fine?.unit ? `${fine.block ? `${fine.block} · ` : ""}${fine.unit}` : fine?.unitId ?? "";

export function EditManagementCompanyRequestPage() {
  const { id = "" } = useParams(); const nav = useNavigate();
  const [request, setRequest] = useState<RequestDetail>(); const [form, setForm] = useState<FormState>({});
  const [files, setFiles] = useState<File[]>([]); const [boleto, setBoleto] = useState<File[]>([]); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const set = (key: string, value: string) => setForm(current => ({ ...current, [key]: value }));
  useEffect(() => { void getRequest(id).then(value => { setRequest(value); const fine = value.fine; const payment = value.payment;
    setForm(value.type === "Fine" ? { unitId: fine?.unitId ?? "", nature: fine?.nature ?? "", description: fine?.description ?? "", date: fine?.occurrenceDate ?? "", value: moneyInput(fine?.value), valueNotDefined: String(fine?.valueNotDefined ?? false) }
      : value.type === "Payment" ? { nature: payment?.nature ?? "", value: String(payment?.value ?? ""), date: payment?.eventDate ?? "", dueDate: payment?.dueDate ?? "", isReimbursement: String(payment?.isReimbursement ?? false), thirdPartyForm: payment?.thirdPartyForm ?? "", notes: payment?.notes ?? "", thirdPartyIdentification: payment?.thirdPartyIdentification ?? "", thirdPartyPixKey: payment?.thirdPartyPixKey ?? "", thirdPartyBank: payment?.thirdPartyBank ?? "", thirdPartyAgency: payment?.thirdPartyAgency ?? "", thirdPartyAccount: payment?.thirdPartyAccount ?? "" }
      : { theme: value.question?.theme ?? "", message: value.messages[0]?.content ?? "" });
  }).catch(() => setError("Não foi possível carregar a solicitação.")); }, [id]);
  const save = async () => { if (!request) return; setSaving(true); setError(""); try { let payload: any;
    if (request.type === "Fine") { const value = form.valueNotDefined === "true" ? null : parseMoneyInput(form.value ?? ""); if (form.valueNotDefined !== "true" && value === null) throw new Error("Informe um valor monetário válido."); payload = { fine: { unitId: form.unitId, nature: form.nature, description: form.description, occurrenceDate: form.date, value, valueNotDefined: form.valueNotDefined === "true" } }; }
    if (request.type === "Payment") payload = { payment: { nature: form.nature, value: Number(form.value), eventDate: form.date, dueDate: form.dueDate || null, isReimbursement: form.isReimbursement === "true", notes: form.notes || null, thirdPartyIdentification: form.thirdPartyIdentification || null, thirdPartyForm: form.thirdPartyForm || null, thirdPartyPixKey: form.thirdPartyPixKey || null, thirdPartyBank: form.thirdPartyBank || null, thirdPartyAgency: form.thirdPartyAgency || null, thirdPartyAccount: form.thirdPartyAccount || null } };
    if (request.type === "GeneralQuestion") payload = { question: { theme: form.theme, message: form.message } }; await updateRequest(id, payload, files, boleto); nav(`/management/administrator/${id}`);
  } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível salvar. Revise os campos."); } finally { setSaving(false); } };
  if (!request) return <PageContainer><Alert severity="error">{error || "Carregando..."}</Alert></PageContainer>;
  if (request.status === "Completed" || request.status === "Cancelled") return <PageContainer><Alert severity="info">Esta solicitação não pode ser editada.</Alert></PageContainer>;
  return <PageContainer maxWidth={800}><Stack spacing={2}><Typography variant="h1">Editar solicitação {request.friendlyIdentifier}</Typography>{error && <Alert severity="error">{error}</Alert>}
    {request.type === "Fine" && <><TextField label="Unidade" value={unitLabel(request.fine)} disabled helperText="A unidade não pode ser alterada nesta edição." /><TextField label="Natureza" value={form.nature ?? ""} onChange={e => set("nature", e.target.value)} /><TextField multiline label="Descrição" value={form.description ?? ""} onChange={e => set("description", e.target.value)} /><TextField type="date" label="Data" value={form.date ?? ""} onChange={e => set("date", e.target.value)} InputLabelProps={{ shrink: true }} /><TextField label="Valor" value={form.value ?? ""} onChange={e => set("value", e.target.value)} InputProps={{ startAdornment: <InputAdornment position="start">R$</InputAdornment> }} /><AttachmentsPreview items={request.attachments} /></>}
    {request.type === "Payment" && <><TextField label="Natureza" value={form.nature ?? ""} onChange={e => set("nature", e.target.value)} /><TextField label="Valor" value={form.value ?? ""} onChange={e => set("value", e.target.value)} /><TextField type="date" label="Vencimento" value={form.dueDate ?? ""} onChange={e => set("dueDate", e.target.value)} InputLabelProps={{ shrink: true }} /><TextField select label="Modalidade" value={form.isReimbursement === "true" ? "Reembolso" : "Terceiro"} onChange={e => set("isReimbursement", String(e.target.value === "Reembolso"))}><MenuItem value="Reembolso">Reembolso</MenuItem><MenuItem value="Terceiro">Terceiro</MenuItem></TextField>{form.isReimbursement !== "true" && <><TextField label="Identificação do terceiro" value={form.thirdPartyIdentification ?? ""} onChange={e => set("thirdPartyIdentification", e.target.value)} /><TextField select label="Forma" value={form.thirdPartyForm ?? ""} onChange={e => set("thirdPartyForm", e.target.value)}><MenuItem value="Pix">PIX</MenuItem><MenuItem value="Boleto">Boleto</MenuItem><MenuItem value="DepositAccount">Conta para depósito</MenuItem></TextField><TextField label="Chave PIX" value={form.thirdPartyPixKey ?? ""} onChange={e => set("thirdPartyPixKey", e.target.value)} /><TextField label="Banco" value={form.thirdPartyBank ?? ""} onChange={e => set("thirdPartyBank", e.target.value)} /><TextField label="Agência" value={form.thirdPartyAgency ?? ""} onChange={e => set("thirdPartyAgency", e.target.value)} /><TextField label="Conta" value={form.thirdPartyAccount ?? ""} onChange={e => set("thirdPartyAccount", e.target.value)} /></>}</>}
    {request.type === "GeneralQuestion" && <><TextField label="Tema" value={form.theme ?? ""} onChange={e => set("theme", e.target.value)} /><TextField multiline label="Texto" value={form.message ?? ""} onChange={e => set("message", e.target.value)} /></>}
    <Button component="label" variant="outlined">Anexos adicionais<input hidden multiple type="file" onChange={e => setFiles(Array.from(e.target.files ?? []))} /></Button>{request.type === "Payment" && form.thirdPartyForm === "Boleto" && <Button component="label" variant="outlined">Boleto<input hidden type="file" onChange={e => setBoleto(Array.from(e.target.files ?? []).slice(0, 1))} /></Button>}<Stack direction="row" justifyContent="space-between"><Button onClick={() => nav(-1)}>Cancelar</Button><Button variant="contained" disabled={saving} onClick={() => void save()}>Salvar</Button></Stack>
  </Stack></PageContainer>;
}
