import { useCallback, useEffect, useState, type FormEvent } from 'react'
import AddRoundedIcon from '@mui/icons-material/AddRounded'
import { Alert, Box, Button, Card, CardContent, Dialog, DialogActions, DialogContent, DialogTitle, Skeleton, Stack, TextField, Typography } from '@mui/material'
import { EmptyState } from '../components/EmptyState'
import { PageContainer } from '../components/PageContainer'
import { useCondominium } from '../condominiums/CondominiumContext'
import { createCategory, listCategories } from '../management/api'
import { managementError } from '../management/errors'
import type { Category } from '../management/types'

export function ManagementCategoriesPage(){const{currentCondominium}=useCondominium();const[items,setItems]=useState<Category[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[success,setSuccess]=useState('');const[open,setOpen]=useState(false);const[name,setName]=useState('');const[description,setDescription]=useState('');const[saving,setSaving]=useState(false)
 const load=useCallback(async()=>{const id=currentCondominium?.condominium.id;if(!id)return;setLoading(true);setItems([]);setError('');try{setItems(await listCategories(id))}catch(e){setError(managementError(e))}finally{setLoading(false)}},[currentCondominium?.condominium.id]);useEffect(()=>{void load()},[load]);
 const submit=async(e:FormEvent)=>{e.preventDefault();const id=currentCondominium?.condominium.id;if(!id||!name.trim()||saving)return;setSaving(true);setError('');try{await createCategory(id,{name:name.trim(),description:description.trim()||null});setOpen(false);setName('');setDescription('');setSuccess('Categoria criada com sucesso.');await load()}catch(err){setError(managementError(err))}finally{setSaving(false)}}
 return <PageContainer><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2}><Box><Typography variant="h1">Categorias</Typography><Typography color="text.secondary">Organize os tipos de solicitação disponíveis aos moradores.</Typography></Box><Button variant="contained" startIcon={<AddRoundedIcon/>} onClick={()=>setOpen(true)}>Nova categoria</Button></Stack>{success&&<Alert severity="success" sx={{mt:2}}>{success}</Alert>}{error&&!open&&<Alert severity="error" sx={{mt:2}} action={<Button onClick={()=>void load()}>Tentar novamente</Button>}>{error}</Alert>}{loading?<Skeleton variant="rounded" height={180} sx={{mt:3}}/>:items.length===0?<EmptyState title="Nenhuma categoria cadastrada" description="Crie categorias para que os moradores consigam abrir solicitações." actionLabel="Nova categoria" onAction={()=>setOpen(true)}/>:<Box display="grid" gridTemplateColumns={{xs:'1fr',sm:'repeat(2,minmax(0,1fr))'}} gap={2} mt={3}>{items.map(item=><Card key={item.id} elevation={0}><CardContent><Typography variant="h2">{item.name}</Typography><Typography color="text.secondary" mt={1}>{item.description||'Sem descrição.'}</Typography></CardContent></Card>)}</Box>}
 <Dialog open={open} onClose={()=>!saving&&setOpen(false)} fullWidth maxWidth="sm"><Box component="form" onSubmit={e=>void submit(e)}><DialogTitle>Nova categoria</DialogTitle><DialogContent><Stack gap={2} pt={1}>{error&&<Alert severity="error">{error}</Alert>}<TextField required label="Nome" value={name} onChange={e=>setName(e.target.value)} slotProps={{htmlInput:{maxLength:100}}}/><TextField label="Descrição" multiline minRows={3} value={description} onChange={e=>setDescription(e.target.value)} slotProps={{htmlInput:{maxLength:500}}} helperText={`${description.length}/500`}/></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)} disabled={saving}>Cancelar</Button><Button type="submit" variant="contained" disabled={saving||!name.trim()}>{saving?'Salvando...':'Criar categoria'}</Button></DialogActions></Box></Dialog></PageContainer>}
