import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router-dom'
import { beforeEach, describe, expect, it, vi } from 'vitest'

const mocks = vi.hoisted(() => ({ listAgenda: vi.fn(), complete: vi.fn(), reactivate: vi.fn(), remove: vi.fn(), context: { activeCondominiumId: 'c1' as string | null, activeCondominium: { id: 'c1', name: 'Monticello', isActive: true } } }))
vi.mock('../agenda/api', () => ({ listAgenda: mocks.listAgenda, completeAgendaReminder: mocks.complete, reactivateAgendaReminder: mocks.reactivate, deleteAgendaReminder: mocks.remove }))
vi.mock('../agenda/AgendaReminderDialog', () => ({ AgendaReminderDialog: ({ open, onClose }: { open: boolean; onClose: () => void }) => open ? <div role="dialog"><span>Editor</span><button onClick={onClose}>Cancelar</button></div> : null }))
vi.mock('../management/ManagementContext', () => ({ useManagementContext: () => mocks.context }))
import { ManagementAgendaPage } from './ManagementAgendaPage'

const active = { id: 'a1', title: 'Inspecao dos extintores', description: 'Conferir blocos', unitId: null, unitIdentifier: null, block: null, relatedThirdParty: 'Prestador X', startsAtUtc: '2026-08-20T15:00:00.000Z', nextOccurrenceAtUtc: '2026-08-20T15:00:00.000Z', timeZoneId: 'America/Sao_Paulo', recurrenceType: 'Weekly' as const, notifyByWhatsApp: true, notifyByEmail: false, isActive: true, completedAt: null, createdAt: '2026-08-19T15:00:00.000Z', requestCount: 1, requestIds: ['r1'], linkedRequests: [{ id: 'r1', protocol: 'ABC12345', title: 'Portao' }] }
const completed = { ...active, id: 'a2', title: 'Lembrete concluido', nextOccurrenceAtUtc: null, isActive: false, completedAt: '2026-08-19T15:00:00.000Z', recurrenceType: 'None' as const, requestCount: 0, requestIds: [], linkedRequests: [] }
const renderPage = (entry = '/management/agenda') => render(<MemoryRouter initialEntries={[entry]}><ManagementAgendaPage /></MemoryRouter>)

describe('ManagementAgendaPage', () => {
  beforeEach(() => { mocks.context.activeCondominiumId = 'c1'; mocks.listAgenda.mockReset().mockResolvedValue([active]); mocks.complete.mockReset().mockResolvedValue(undefined); mocks.reactivate.mockReset().mockResolvedValue(undefined); mocks.remove.mockReset().mockResolvedValue(undefined) })
  it('renders views through the existing API contract', async () => { const user = userEvent.setup(); renderPage(); expect(await screen.findByText('Inspecao dos extintores')).toBeInTheDocument(); await user.click(screen.getByRole('tab', { name: 'Recorrentes' })); await waitFor(() => expect(mocks.listAgenda).toHaveBeenCalledWith('c1', 'recurring', '')); await user.click(screen.getByRole('tab', { name: /Conclu/ })); await waitFor(() => expect(mocks.listAgenda).toHaveBeenCalledWith('c1', 'past', '')) })
  it('keeps loading, error and specific empty states distinct', async () => { let resolve!: (items: typeof active[]) => void; mocks.listAgenda.mockReturnValueOnce(new Promise(r => { resolve = r })); const view = renderPage(); expect(document.querySelector('.MuiSkeleton-root')).toBeInTheDocument(); resolve([]); expect(await screen.findByText(/Nenhum lembrete ativo/)).toBeInTheDocument(); view.unmount(); mocks.listAgenda.mockRejectedValueOnce(new Error('offline')); const errorView = renderPage(); expect(await screen.findByText(/N.*foi poss/)).toBeInTheDocument(); expect(screen.queryByText(/Nenhum lembrete ativo/)).not.toBeInTheDocument(); errorView.unmount() })
  it('requires a condominium and discards stale responses', async () => { mocks.context.activeCondominiumId = null; renderPage(); expect(screen.getByText(/Este m.*dulo trabalha com um condom/)).toBeInTheDocument(); let first!: (items: typeof active[]) => void; let second!: (items: typeof active[]) => void; mocks.context.activeCondominiumId = 'c1'; mocks.listAgenda.mockImplementationOnce(() => new Promise(r => { first = r })).mockImplementationOnce(() => new Promise(r => { second = r })); const view = renderPage(); mocks.context.activeCondominiumId = 'c2'; view.rerender(<MemoryRouter><ManagementAgendaPage /></MemoryRouter>); second([{ ...active, id: 'b1', title: 'Condominio B' }]); expect(await screen.findByText('Condominio B')).toBeInTheDocument(); first([{ ...active, title: 'Condominio A' }]); await waitFor(() => expect(screen.queryByText('Condominio A')).not.toBeInTheDocument()) })
  it('focuses a valid reminder and ignores an inaccessible id', async () => { renderPage('/management/agenda?reminderId=a1'); expect(await screen.findByText('Inspecao dos extintores')).toBeInTheDocument(); expect(document.getElementById('agenda-reminder-a1')).toHaveAttribute('aria-current', 'true'); renderPage('/management/agenda?reminderId=missing'); await waitFor(() => expect(mocks.listAgenda).toHaveBeenCalled()) })
  it('preserves linked requests and domain completion state', async () => { mocks.listAgenda.mockResolvedValueOnce([active, completed]); renderPage('/management/agenda?reminderId=a2'); expect(await screen.findByText('Lembrete concluido')).toBeInTheDocument(); expect(screen.getAllByText(/Conclu/).some(element => element.tagName === 'SPAN')).toBe(true); expect(screen.getByRole('button', { name: 'Atendimento #ABC12345' })).toBeInTheDocument() })
  it('supports create, edit, complete and delete actions', async () => { const user = userEvent.setup(); renderPage(); await screen.findByText('Inspecao dos extintores'); await user.click(screen.getByRole('button', { name: /Novo lembrete/ })); expect(screen.getByRole('dialog')).toBeInTheDocument(); await user.click(screen.getByRole('button', { name: 'Cancelar' })); await user.click(screen.getByRole('button', { name: /Mais .* Inspec/ })); await user.click(screen.getByRole('menuitem', { name: 'Editar' })); expect(screen.getByRole('dialog')).toBeInTheDocument(); await user.click(screen.getByRole('button', { name: 'Cancelar' })); await user.click(screen.getByRole('button', { name: /Concluir Inspec/ })); await waitFor(() => expect(mocks.complete).toHaveBeenCalledWith('c1', 'a1')); await user.click(screen.getByRole('button', { name: /Mais .* Inspec/ })); await user.click(screen.getByRole('menuitem', { name: 'Excluir' })); expect(screen.getByText(/Este lembrete est/)).toBeInTheDocument() })
})
