import { useCallback, useEffect, useState } from 'react'
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Skeleton, Stack, Tab, Tabs, TextField, Typography } from '@mui/material'
import AddRoundedIcon from '@mui/icons-material/AddRounded'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { PageContainer } from '../components/PageContainer'
import { ManagementCondominiumSwitcher } from '../management/components/ManagementCondominiumSwitcher'
import { useManagementContext } from '../management/ManagementContext'
import { AgendaReminderDialog } from '../agenda/AgendaReminderDialog'
import { completeAgendaReminder, deleteAgendaReminder, listAgenda, reactivateAgendaReminder } from '../agenda/api'
import type { AgendaReminder } from '../agenda/types'

const recurrence = { None: 'Não repete', Weekly: 'Semanal', Monthly: 'Mensal' }
export function ManagementAgendaPage() {
  const { activeCondominiumId } = useManagementContext(), navigate = useNavigate(); const [params, setParams] = useSearchParams()
  const [items, setItems] = useState<AgendaReminder[]>([]), [view, setView] = useState('upcoming'), [search, setSearch] = useState('')
  const [loading, setLoading] = useState(true), [error, setError] = useState(''), [dialog, setDialog] = useState(false), [editing, setEditing] = useState<AgendaReminder | null>(null), [deleting, setDeleting] = useState<AgendaReminder | null>(null), [reactivateAfterEdit, setReactivateAfterEdit] = useState<string | null>(null)
  const load = useCallback(async () => { if (!activeCondominiumId) return; setLoading(true); try { setItems(await listAgenda(activeCondominiumId, view, search)); setError('') } catch { setError('Não foi possível carregar a Agenda.') } finally { setLoading(false) } }, [activeCondominiumId, view, search])
  useEffect(() => { void load() }, [load]); useEffect(() => { if (params.get('create') === 'true' && params.get('requestId')) { setEditing(null); setDialog(true) } }, [params])
  const close = () => { setDialog(false); setEditing(null); setReactivateAfterEdit(null); if (params.has('requestId') || params.has('create')) { const next = new URLSearchParams(params); next.delete('requestId'); next.delete('create'); setParams(next, { replace: true }) } }
  const run = async (action: () => Promise<void>) => { try { await action(); await load() } catch { setError('Não foi possível concluir a ação.') } }
  const reactivate = (item: AgendaReminder) => { if (!activeCondominiumId) return; if (item.recurrenceType === 'None' && new Date(item.startsAtUtc) <= new Date()) { setEditing(item); setReactivateAfterEdit(item.id); setDialog(true); return } void run(() => reactivateAgendaReminder(activeCondominiumId, item.id)) }
  const saved = async () => { if (reactivateAfterEdit && activeCondominiumId) { const id = reactivateAfterEdit; close(); await run(() => reactivateAgendaReminder(activeCondominiumId, id)); return } close(); await load() }
  return <PageContainer maxWidth={1200}><Stack spacing={2}>
    <Box display="flex" justifyContent="space-between" gap={2} flexWrap="wrap"><Box><Typography variant="h1">Agenda</Typography><Typography color="text.secondary">Lembretes e compromissos operacionais do condomínio.</Typography></Box><Button variant="contained" startIcon={<AddRoundedIcon />} onClick={() => { setEditing(null); setDialog(true) }}>Novo lembrete</Button></Box>
    <ManagementCondominiumSwitcher /><Tabs value={view} onChange={(_, value) => setView(value)} variant="scrollable"><Tab value="upcoming" label="Próximos" /><Tab value="recurring" label="Recorrentes" /><Tab value="past" label="Concluídos" /></Tabs><TextField size="small" label="Buscar por título ou terceiro" value={search} onChange={event => setSearch(event.target.value)} />
    {error && <Alert severity="error">{error}</Alert>}{loading ? <Skeleton height={180} /> : items.length === 0 ? <Alert severity="info">Nenhum lembrete nesta visão.</Alert> : <Stack spacing={1.5}>{items.map(item => <Card key={item.id} variant="outlined"><CardContent><Box display="flex" justifyContent="space-between" gap={2} flexWrap="wrap"><Box><Typography fontWeight={800}>{item.title}</Typography><Typography color="text.secondary">{item.description || 'Sem descrição'}</Typography><Typography mt={1}>{item.nextOccurrenceAtUtc ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(item.nextOccurrenceAtUtc)) : 'Concluído'}</Typography><Typography variant="body2">{item.block ? `${/^bloco /i.test(item.block) ? item.block : `Bloco ${item.block}`} · ` : ''}{item.unitIdentifier ? `Apto ${item.unitIdentifier}` : ''}{item.relatedThirdParty ? `${item.unitIdentifier ? ' · ' : ''}${item.relatedThirdParty}` : ''}</Typography></Box><Stack direction="row" spacing={1} flexWrap="wrap"><Chip label={recurrence[item.recurrenceType]} /><Chip label={`${item.requestCount} atendimento(s)`} /><Chip label={[item.notifyByWhatsApp && 'WhatsApp', item.notifyByEmail && 'E-mail'].filter(Boolean).join(' + ') || 'Somente Agenda'} /></Stack></Box>
      <Box mt={2}><Button onClick={() => { setEditing(item); setDialog(true) }}>Editar</Button>{item.isActive ? <Button color="success" onClick={() => activeCondominiumId && void run(() => completeAgendaReminder(activeCondominiumId, item.id))}>Marcar como concluído</Button> : <Button color="success" onClick={() => reactivate(item)}>Reativar</Button>}<Button color="error" onClick={() => setDeleting(item)}>Excluir</Button></Box>
      {item.linkedRequests.length > 0 && <Box mt={1.5} pt={1.5} borderTop="1px solid" borderColor="divider"><Typography variant="body2" color="text.secondary" component="span">{item.linkedRequests.length === 1 ? 'Atendimento: ' : 'Atendimentos: '}</Typography>{item.linkedRequests.map((request, index) => <Button key={request.id} size="small" sx={{ minWidth: 0, px: .5 }} onClick={() => navigate(`/management/requests/${request.id}`)}>#{request.protocol}{index < item.linkedRequests.length - 1 ? ' ·' : ''}</Button>)}</Box>}
    </CardContent></Card>)}</Stack>}
  </Stack>{activeCondominiumId && <AgendaReminderDialog open={dialog} condominiumId={activeCondominiumId} reminder={editing} initialRequestId={params.get('requestId') ?? undefined} onClose={close} onSaved={() => void saved()} />}
  <Dialog open={Boolean(deleting)} onClose={() => setDeleting(null)}><DialogTitle>Excluir lembrete?</DialogTitle><DialogContent>{deleting?.requestCount ? `Este lembrete está vinculado a ${deleting.requestCount} atendimento(s). Ao excluir, os vínculos serão removidos. Os atendimentos não serão excluídos.` : 'Esta ação não pode ser desfeita.'}</DialogContent><DialogActions><Button onClick={() => setDeleting(null)}>Cancelar</Button><Button color="error" onClick={() => { if (!deleting || !activeCondominiumId) return; void run(() => deleteAgendaReminder(activeCondominiumId, deleting.id)).then(() => setDeleting(null)) }}>Excluir</Button></DialogActions></Dialog>
  </PageContainer>
}
