import { useEffect, useState, type FormEvent } from 'react'
import { Alert, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography, IconButton, Menu, Tooltip } from '@mui/material'
import { PageContainer } from '../../components/PageContainer'
import { listOverwatchCondominiums } from '../condominiums/api'
import type { OverwatchCondominium } from '../condominiums/types'
import { createSubManager, listSubManagers, setSubManagerStatus, listSubManagerPermissions, updateSubManagerPermissions, resendSubManagerFirstAccess, resetSubManagerPassword, updateSubManager, subManagerModules, type PixKeyType, type SubManager, type SubManagerModule } from '../submanagers/api'
import { PixFields } from '../components/PixFields'

const labels: Record<SubManagerModule, string> = { Requests: 'Solicitações', Attendance: 'Atendimento', ManagementCompany: 'Administradora', Agenda: 'Agenda', Assistant: 'Assistente', Documents: 'Documentos', Management: 'Gestão' }
const emptyForm = () => ({ fullName: '', email: '', phoneNumber: '', condominiumId: '', pixKeyType: '' as PixKeyType | '', pixKey: '' })

export function OverwatchSubManagersPage() {
  const [items, setItems] = useState<SubManager[]>([]); const [condominiums, setCondominiums] = useState<OverwatchCondominium[]>([])
  const [open, setOpen] = useState(false); const [error, setError] = useState(''); const [credentials, setCredentials] = useState<{ email: string; temporaryPassword: string } | null>(null)
  const [form, setForm] = useState(emptyForm); const [editing, setEditing] = useState<SubManager | null>(null); const [permissionTarget, setPermissionTarget] = useState<SubManager | null>(null); const [permissions, setPermissions] = useState<Record<string, boolean>>({}); const [menuTarget, setMenuTarget] = useState<{ item: SubManager; anchor: HTMLElement } | null>(null)
  const load = async () => { const [people, condos] = await Promise.all([listSubManagers(), listOverwatchCondominiums()]); setItems(people); setCondominiums(condos) }
  useEffect(() => { void load() }, [])
  const closeCreate = () => { setOpen(false); setEditing(null); setForm(emptyForm()) }
  const openEdit = (item: SubManager) => { setEditing(item); setForm({ fullName: item.fullName, email: item.email, phoneNumber: item.phoneNumber ?? '', condominiumId: item.condominiumId, pixKeyType: item.pixKeyType ?? '', pixKey: item.pixKey ?? '' }); setOpen(true) }
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); try { const created = await createSubManager({ ...form, phoneNumber: form.phoneNumber || null, pixKeyType: form.pixKeyType || null, pixKey: form.pixKey || null }); setCredentials(created); closeCreate(); await load() } catch { setError('Não foi possível cadastrar o subsíndico. Verifique vínculos e dados informados.') } }
  const openPermissions = async (item: SubManager) => { setPermissionTarget(item); const rows = await listSubManagerPermissions(item.id); setPermissions(Object.fromEntries(rows.map(x => [x.module, x.allowed]))) }
  const resetPassword = async (item: SubManager) => { const result = await resetSubManagerPassword(item); setCredentials({ email: item.email, temporaryPassword: result.temporaryPassword }) }
  return <PageContainer>
    <Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" gap={2}><Box><Typography variant="h1">Subsíndicos</Typography><Typography color="text.secondary">Cada subsíndico pode possuir um único vínculo ativo.</Typography></Box><Button variant="contained" onClick={() => { setForm(emptyForm()); setOpen(true) }}>Novo subsíndico</Button></Stack>
    {error && <Alert severity="error" sx={{ mt: 2 }}>{error}</Alert>}
    <Paper variant="outlined" sx={{ mt: 3, overflowX: 'auto' }}><Table><TableHead><TableRow>{['Nome', 'Condomínio', 'E-mail', 'PIX', 'Status', 'Ação'].map(x => <TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{items.map(item => <TableRow key={`${item.id}-${item.condominiumId}`}><TableCell>{item.fullName}</TableCell><TableCell>{item.condominiumName}</TableCell><TableCell>{item.email}</TableCell><TableCell>{item.pixKey ? `${item.pixKeyType}: ${item.pixKey}` : 'Não informado'}</TableCell><TableCell>{item.isActive && item.hasActiveLink ? 'Ativo' : 'Inativo'}</TableCell><TableCell><Button size="small" onClick={async () => { await setSubManagerStatus(item.id, !item.isActive); await load() }}>{item.isActive ? 'Inativar' : 'Ativar'}</Button><Button size="small" onClick={() => void openPermissions(item)}>Permissões</Button><Button size="small" onClick={() => void resendSubManagerFirstAccess(item)}>Reenviar primeiro acesso</Button><Button size="small" onClick={() => void resetPassword(item)}>Redefinir senha</Button></TableCell></TableRow>)}</TableBody></Table></Paper>
    <Dialog open={open} onClose={closeCreate} fullWidth maxWidth="sm"><Box component="form" onSubmit={event => void submit(event)}><DialogTitle>Novo subsíndico</DialogTitle><DialogContent><Stack gap={2} pt={1}><TextField required label="Nome" value={form.fullName} onChange={e => setForm({ ...form, fullName: e.target.value })}/><TextField required type="email" label="E-mail" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/><TextField label="Telefone" value={form.phoneNumber} onChange={e => setForm({ ...form, phoneNumber: e.target.value })}/><TextField select required label="Condomínio" value={form.condominiumId} onChange={e => setForm({ ...form, condominiumId: e.target.value })}>{condominiums.map(item => <MenuItem key={item.id} value={item.id}>{item.name}</MenuItem>)}</TextField><PixFields type={form.pixKeyType} pixKey={form.pixKey} onTypeChange={value => setForm({ ...form, pixKeyType: value })} onKeyChange={value => setForm({ ...form, pixKey: value })} /></Stack></DialogContent><DialogActions><Button onClick={closeCreate}>Cancelar</Button><Button type="submit" variant="contained">Cadastrar</Button></DialogActions></Box></Dialog>
    <Dialog open={Boolean(permissionTarget)} onClose={() => setPermissionTarget(null)} fullWidth maxWidth="sm"><DialogTitle>Permissões de acesso</DialogTitle><DialogContent><Stack>{subManagerModules.map(module => <Stack key={module} direction="row" justifyContent="space-between" alignItems="center"><Typography>{labels[module]}</Typography><Button onClick={() => setPermissions(x => ({ ...x, [module]: !x[module] }))}>{permissions[module] ? 'Permitido' : 'Sem acesso'}</Button></Stack>)}</Stack></DialogContent><DialogActions><Button onClick={() => setPermissionTarget(null)}>Cancelar</Button><Button variant="contained" onClick={async () => { if (permissionTarget) await updateSubManagerPermissions(permissionTarget.id, subManagerModules.map(module => ({ module, allowed: permissions[module] ?? true }))); setPermissionTarget(null) }}>Salvar</Button></DialogActions></Dialog>
    <Dialog open={Boolean(credentials)} onClose={() => setCredentials(null)}><DialogTitle>Credenciais temporárias</DialogTitle><DialogContent>{credentials && <Alert severity="warning">E-mail: {credentials.email}<br/>Senha: {credentials.temporaryPassword}</Alert>}</DialogContent><DialogActions><Button onClick={() => setCredentials(null)}>Concluir</Button></DialogActions></Dialog>
  </PageContainer>
}
