import { useCallback, useEffect, useState } from 'react'
import RefreshRoundedIcon from '@mui/icons-material/RefreshRounded'
import DownloadRoundedIcon from '@mui/icons-material/DownloadRounded'
import ExpandMoreRoundedIcon from '@mui/icons-material/ExpandMoreRounded'
import { Accordion, AccordionDetails, AccordionSummary, Alert, Box, Button, Card, CardContent, Chip, Grid, Skeleton, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Tooltip, Typography } from '@mui/material'
import { PageContainer } from '../../components/PageContainer'
import { useVisiblePolling } from '../../hooks/useVisiblePolling'
import { downloadSystemDiagnostic, duration, getSystemStatus, statusLabel, type HealthState, type SystemStatus } from '../system'
const stateColor = (s: HealthState): 'success'|'warning'|'error'|'default' => s === 'Healthy' ? 'success' : s === 'Unhealthy' ? 'error' : s === 'Disabled' ? 'default' : 'warning'
const showDate = (v?: string) => v ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'medium' }).format(new Date(v)) : '—'
function State({ value }: { value: HealthState }) { return <Chip size="small" color={stateColor(value)} label={statusLabel[value]} /> }
export function OverwatchSystemPage() {
  const [data,setData]=useState<SystemStatus|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [generating,setGenerating]=useState(false); const [diagnosticError,setDiagnosticError]=useState('')
  const load=useCallback(async()=>{try{setError('');setData(await getSystemStatus())}catch{setError('Não foi possível carregar a saúde do sistema.')}finally{setLoading(false)}},[])
  useEffect(()=>{void load()},[load]); const poll=useCallback(()=>load(),[load]); useVisiblePolling(poll,30_000)
  const download=async()=>{setGenerating(true);setDiagnosticError('');try{await downloadSystemDiagnostic()}catch{setDiagnosticError('Não foi possível gerar o diagnóstico.')}finally{setGenerating(false)}}
  return <PageContainer><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2}><Box><Typography variant="h1">Sistema</Typography><Typography color="text.secondary" mt={1}>Saúde e atividade operacional da Comvy.</Typography></Box><Stack direction="row" gap={1}><Button variant="outlined" startIcon={<RefreshRoundedIcon/>} onClick={()=>void load()}>Atualizar</Button><Button variant="contained" startIcon={<DownloadRoundedIcon/>} disabled={generating} onClick={()=>void download()}>{generating?'Gerando diagnóstico...':'Exportar diagnóstico'}</Button></Stack></Stack>
  {diagnosticError&&<Alert severity="error" sx={{mt:2}}>{diagnosticError}</Alert>}
  {data && data.globalStatus !== 'Healthy' && (data.reasons?.length ?? 0) > 0 && <Alert severity="warning" sx={{mt:2}}><Typography fontWeight={700}>Motivos</Typography>{data.reasons?.map(reason => <Typography key={reason} variant="body2">{reason}</Typography>)}</Alert>}
  {error&&<Alert severity="error" sx={{mt:2}} action={<Button color="inherit" onClick={()=>void load()}>Tentar novamente</Button>}>{error}</Alert>}
  {loading&&!data?<Skeleton variant="rounded" height={180} sx={{mt:3}}/>:data&&<>
    <Card elevation={0} sx={{mt:3,borderLeft:5,borderColor:`${stateColor(data.globalStatus)}.main`}}><CardContent><Typography variant="overline">Comvy Status</Typography><Stack direction="row" alignItems="center" gap={2}><Typography variant="h2">{{Healthy:'Operacional',Degraded:'Degradado',Unhealthy:'Crítico',Unknown:'Desconhecido',Disabled:'Desabilitado'}[data.globalStatus]}</Typography><State value={data.globalStatus}/></Stack><Typography variant="caption" color="text.secondary">Atualizado em {showDate(data.generatedAt)}</Typography></CardContent></Card>
    <Accordion elevation={0} sx={{mt:2}}><AccordionSummary expandIcon={<ExpandMoreRoundedIcon/>}><Typography fontWeight={700}>Como interpretar este painel</Typography></AccordionSummary><AccordionDetails><Typography variant="body2">Saudável indica operação normal; Degradado indica deterioração relevante; Crítico indica falha severa. Média é o tempo médio de todas as requisições. P95 é o tempo em que 95% terminaram. Para operações interativas, abaixo de 500 ms é uma boa referência; 500–1000 ms pede atenção e acima de 1000 ms merece investigação. Em 5xx, abaixo de 1% é saudável, 1–5% pede atenção e acima de 5% é crítico. Queries/request, queries acima de 500 ms e payload são indicadores para investigação, não falhas isoladas. Filas devem ser avaliadas pelo acúmulo e idade. Abaixo de 20 chamadas é uma amostra pequena.</Typography></AccordionDetails></Accordion>
    <Grid container spacing={2} mt={.5}>{data.components.map(c=><Grid key={c.name} size={{xs:12,sm:6,lg:4}}><Card elevation={0} sx={{height:'100%'}}><CardContent><Stack direction="row" justifyContent="space-between"><Typography fontWeight={800}>{c.name}</Typography><State value={c.status}/></Stack><Typography color="text.secondary" mt={2}>{c.detail}</Typography></CardContent></Card></Grid>)}</Grid>
    <Typography variant="h2" mt={4} mb={2}>Atividade — últimas 24h</Typography><Grid container spacing={2}>{Object.entries(data.activity24h).map(([k,v])=><Grid key={k} size={{xs:6,md:2.4}}><Card elevation={0}><CardContent><Typography variant="h3">{v}</Typography><Typography variant="caption" color="text.secondary">{{requestsCreated:'Solicitações',whatsappReceived:'WhatsApp recebidos',whatsappSent:'WhatsApp enviados',aiCalls:'Chamadas IA',operationalErrors:'Erros'}[k]}</Typography></CardContent></Card></Grid>)}</Grid>
    <Typography variant="h2" mt={4} mb={2}>Workers</Typography><TableContainer component={Card}><Table size="small"><TableHead><TableRow><TableCell>Worker / instância</TableCell><TableCell>Estado</TableCell><TableCell>Heartbeat</TableCell><TableCell>Última execução</TableCell><TableCell>Resultado</TableCell></TableRow></TableHead><TableBody>{data.workers.map(w=><TableRow key={`${w.workerName}-${w.instanceId}`}><TableCell><b>{w.workerName}</b><br/><Typography variant="caption">{w.instanceId}</Typography></TableCell><TableCell><State value={w.status}/></TableCell><TableCell>{showDate(w.lastHeartbeatAt)}</TableCell><TableCell>{showDate(w.lastCompletedAt)}</TableCell><TableCell>{w.lastSucceeded==null?'—':w.lastSucceeded?`${w.lastProcessedItems??0} itens`:w.lastResultCode??'Falha'}</TableCell></TableRow>)}</TableBody></Table></TableContainer>
    <Grid container spacing={2} mt={2}><Grid size={{xs:12,lg:5}}><Typography variant="h2" mb={2}>WhatsApp</Typography><Card elevation={0}><CardContent><Stack direction="row" justifyContent="space-between"><Typography fontWeight={800}>Fila outbound</Typography><State value={data.whatsapp.status}/></Stack><Grid container spacing={2} mt={1}>{[['Na fila',data.whatsapp.queued],['Enviando',data.whatsapp.sending],['Falhas',data.whatsapp.failed],['Entregues',data.whatsapp.delivered],['Lidas',data.whatsapp.read],['Enviadas/24h',data.whatsapp.sent24h]].map(([l,v])=><Grid key={String(l)} size={6}><Typography variant="h3">{v}</Typography><Typography variant="caption">{l}</Typography></Grid>)}</Grid><Typography mt={2}>Item mais antigo: {duration(data.whatsapp.oldestQueuedAgeSeconds)} · {data.whatsapp.failed24h} falhas/24h</Typography><Typography variant="caption">Último webhook: {showDate(data.whatsapp.lastWebhookReceived)}</Typography></CardContent></Card></Grid>
    <Grid size={{xs:12,lg:7}}><Typography variant="h2" mb={2}>IA</Typography><Card elevation={0}><CardContent><Stack direction="row" justifyContent="space-between"><Typography fontWeight={800}>OpenAI</Typography><State value={data.ai.status}/></Stack><Table size="small"><TableHead><TableRow><TableCell>Período</TableCell><TableCell>Chamadas</TableCell><TableCell>Sucesso</TableCell><TableCell>Média / P95</TableCell><TableCell>Tokens</TableCell></TableRow></TableHead><TableBody>{data.ai.periods.map(p=><TableRow key={p.period}><TableCell>{p.period}</TableCell><TableCell>{p.metrics.calls}</TableCell><TableCell>{p.metrics.successRate==null?'Sem atividade':`${p.metrics.successRate}%`}</TableCell><TableCell>{p.metrics.averageLatencyMs??'—'} / {p.metrics.p95LatencyMs??'—'} ms</TableCell><TableCell>{p.metrics.totalTokens.toLocaleString('pt-BR')}</TableCell></TableRow>)}</TableBody></Table>{data.ai.breakdown.length>0&&<><Typography fontWeight={800} mt={2}>Por operação / modelo</Typography>{data.ai.breakdown.map(x=><Typography key={`${x.operation}-${x.model}`}>{x.operation} · {x.model??'modelo não informado'} — {x.metrics.calls} chamadas, {x.metrics.totalTokens.toLocaleString('pt-BR')} tokens</Typography>)}</>}</CardContent></Card></Grid></Grid>
    <Typography variant="h2" mt={4} mb={2}>E-mail</Typography><Card elevation={0}><CardContent><Stack direction="row" justifyContent="space-between"><Typography>{data.email.enabled ? (data.email.configured ? 'Configuração presente' : 'Configuração incompleta') : 'Desabilitado por configuração'}</Typography><State value={data.email.status}/></Stack><Typography mt={1}>{data.email.successes24h} envios e {data.email.failures24h} falhas nas últimas 24h · último envio {showDate(data.email.lastSend)}</Typography></CardContent></Card>
    <Typography variant="h2" mt={4} mb={2}>Performance da API</Typography><Grid container spacing={2}>{data.performance.periods.map(p=><Grid key={p.period} size={{xs:12,md:6}}><Card elevation={0}><CardContent><Typography fontWeight={800}>Últimas {p.period}</Typography><Typography>{p.requests} requests · média {p.averageMs} ms · <Tooltip title="95% das requisições foram concluídas em até este tempo."><span>P95 {p.p95Ms} ms</span></Tooltip> · {p.errors5xx} erros 5xx ({p.errorRate5xx}%)</Typography>{p.sampleSmall&&<Typography variant="caption" color="text.secondary">Amostra pequena</Typography>}<Typography color="text.secondary">{p.averageQueries} queries/request · {p.slowQueries} queries acima de 500 ms · payload médio {Math.round(p.averageResponseBytes/1024)} KB</Typography></CardContent></Card></Grid>)}</Grid>
    <TableContainer component={Card} sx={{mt:2}}><Table size="small"><TableHead><TableRow><TableCell>Endpoint</TableCell><TableCell>Chamadas</TableCell><TableCell>Média</TableCell><TableCell>P95</TableCell><TableCell>Queries média/máx.</TableCell><TableCell>Payload</TableCell></TableRow></TableHead><TableBody>{data.performance.topSlowest.map(e=><TableRow key={`${e.method}-${e.route}`} sx={{bgcolor:!e.isHeavyOperation&&!e.sampleSmall?(e.p95Ms>1000?'warning.main':e.p95Ms>=500?'action.hover':undefined):undefined}}><TableCell>{e.method} {e.route}<br/><Typography variant="caption">{e.isHeavyOperation?'Operação pesada':e.sampleSmall?'Amostra pequena':'Interativo'}</Typography></TableCell><TableCell>{e.calls}</TableCell><TableCell>{e.averageMs} ms</TableCell><TableCell>{e.p95Ms} ms</TableCell><TableCell>{e.averageQueries} / {e.maximumQueries}</TableCell><TableCell>{Math.round(e.averageResponseBytes/1024)} KB</TableCell></TableRow>)}</TableBody></Table></TableContainer>
    <Typography variant="h2" mt={4} mb={2}>Erros recentes</Typography><TableContainer component={Card}><Table size="small"><TableHead><TableRow><TableCell>Horário</TableCell><TableCell>Componente</TableCell><TableCell>Categoria</TableCell><TableCell>Razão segura</TableCell></TableRow></TableHead><TableBody>{data.recentEvents.filter(e=>e.severity==='Error').slice(0,10).map((e,i)=><TableRow key={`${e.timestamp}-${i}`}><TableCell>{showDate(e.timestamp)}</TableCell><TableCell>{e.component}</TableCell><TableCell>{e.category}</TableCell><TableCell>{e.reasonCode}</TableCell></TableRow>)}</TableBody></Table></TableContainer>
  </>}</PageContainer>
}
