import { useCallback, useEffect, useState } from "react";
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from "@mui/material";
import { PageContainer } from "../../components/PageContainer";
import { api } from "../../services/api";
import { permanentlyDeleteManagementCompanyRequest } from "../managementCompanies/api";
type Item={id:string;friendlyIdentifier:string;type:string;status:string;condominiumName:string;managementCompanyName:string;createdByName:string;createdAt:string};
export function OverwatchManagementCompanyRequestsPage(){const [items,setItems]=useState<Item[]>([]),[search,setSearch]=useState(""),[selected,setSelected]=useState<Item|null>(null),[confirmation,setConfirmation]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);try{setItems((await api.get<{items:Item[]}>('/overwatch/management-company-requests',{params:{search:search||undefined,page:1}})).data.items)}catch{setError("Não foi possível carregar as solicitações.")}finally{setLoading(false)}},[search]);useEffect(()=>{void load()},[load]);
 const remove=async()=>{if(!selected||confirmation!==selected.friendlyIdentifier)return;try{await permanentlyDeleteManagementCompanyRequest(selected.id,confirmation);setSelected(null);setConfirmation("");await load()}catch{setError("Não foi possível excluir a solicitação.")}};
 return <PageContainer><Stack spacing={2}><Typography variant="h1">Solicitações Gestão ↔ Administradora</Typography><Stack direction="row" gap={1}><TextField size="small" label="Buscar FriendlyIdentifier" value={search} onChange={e=>setSearch(e.target.value)} /><Button variant="outlined" onClick={()=>void load()}>Buscar</Button></Stack>{error&&<Alert severity="error">{error}</Alert>}<Table size="small"><TableHead><TableRow>{["Identificador","Tipo","Condomínio","Administradora","Status","Criador","Data","Ação"].map(x=><TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{!loading&&items.map(item=><TableRow key={item.id}><TableCell>{item.friendlyIdentifier}</TableCell><TableCell>{item.type}</TableCell><TableCell>{item.condominiumName}</TableCell><TableCell>{item.managementCompanyName}</TableCell><TableCell>{item.status}</TableCell><TableCell>{item.createdByName}</TableCell><TableCell>{new Date(item.createdAt).toLocaleDateString("pt-BR")}</TableCell><TableCell><Button color="error" size="small" onClick={()=>setSelected(item)}>Excluir definitivamente</Button></TableCell></TableRow>)}</TableBody></Table></Stack><Dialog open={Boolean(selected)} onClose={()=>setSelected(null)} fullWidth maxWidth="sm"><DialogTitle>Excluir definitivamente?</DialogTitle><DialogContent><Typography>Esta ação excluirá permanentemente a solicitação {selected?.friendlyIdentifier}, suas mensagens, eventos e anexos. Esta ação não pode ser desfeita.</Typography><TextField autoFocus fullWidth label="Digite o FriendlyIdentifier exato" value={confirmation} onChange={e=>setConfirmation(e.target.value)} sx={{mt:2}} /></DialogContent><DialogActions><Button onClick={()=>setSelected(null)}>Cancelar</Button><Button color="error" variant="contained" disabled={!selected||confirmation!==selected.friendlyIdentifier} onClick={()=>void remove()}>Excluir definitivamente</Button></DialogActions></Dialog></PageContainer>}
