import { useEffect, useState, type FormEvent } from 'react'
import { AdminPanelSettings, Edit, LockReset, MoreVert, Send, Settings } from '@mui/icons-material'
import { Alert, Autocomplete, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, Menu, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Tooltip, Typography } from '@mui/material'
import { PageContainer } from '../../components/PageContainer'
import { listOverwatchCondominiums } from '../condominiums/api'
import type { OverwatchCondominium } from '../condominiums/types'
import { createSubManager, listSubManagers, searchExistingUsers, setSubManagerStatus, listSubManagerPermissions, updateSubManagerPermissions, resendSubManagerFirstAccess, resetSubManagerPassword, updateSubManager, subManagerModules, type ExistingUser, type PixKeyType, type SubManager, type SubManagerModule } from '../submanagers/api'
import { PixFields } from '../components/PixFields'
import { getErrorMessage } from '../../services/api'

const labels: Record<SubManagerModule, string> = { Requests: 'Solicitações', Attendance: 'Atendimento', ManagementCompany: 'Administradora', Agenda: 'Agenda', Assistant: 'Assistente', Documents: 'Documentos', Management: 'Gestão' }
const emptyForm = () => ({ fullName: '', email: '', phoneNumber: '', condominiumId: '', pixKeyType: '' as PixKeyType | '', pixKey: '' })

export function OverwatchSubManagersPage() {
  const [items, setItems] = useState<SubManager[]>([]); const [condominiums, setCondominiums] = useState<OverwatchCondominium[]>([]); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<SubManager | null>(null); const [error, setError] = useState(''); const [credentials, setCredentials] = useState<{ email: string; temporaryPassword: string } | null>(null); const [form, setForm] = useState(emptyForm); const [mode, setMode] = useState<'new' | 'existing'>('new'); const [existingQuery, setExistingQuery] = useState(''); const [existingUsers, setExistingUsers] = useState<ExistingUser[]>([]); const [selectedExisting, setSelectedExisting] = useState<ExistingUser | null>(null); const [permissionTarget, setPermissionTarget] = useState<SubManager | null>(null); const [permissions, setPermissions] = useState<Record<string, boolean>>({}); const [menu, setMenu] = useState<{ item: SubManager; anchor: HTMLElement } | null>(null)
  const load = async () => { const [people, condos] = await Promise.all([listSubManagers(), listOverwatchCondominiums()]); setItems(people); setCondominiums(condos) }; useEffect(() => { void load() }, [])
  const closeForm = () => { setOpen(false); setEditing(null); setForm(emptyForm()); setMode('new'); setExistingQuery(''); setExistingUsers([]); setSelectedExisting(null) }
  const openEdit = (item: SubManager) => { setEditing(item); setForm({ fullName: item.fullName, email: item.email, phoneNumber: item.phoneNumber ?? '', condominiumId: item.condominiumId, pixKeyType: item.pixKeyType ?? '', pixKey: item.pixKey ?? '' }); setOpen(true) }
  useEffect(() => { const query = existingQuery.trim(); if (mode !== 'existing' || query.length < 2 || !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(form.condominiumId)) { setExistingUsers([]); return } const controller = new AbortController(); const timer = window.setTimeout(() => { void searchExistingUsers(query, form.condominiumId, controller.signal).then(setExistingUsers).catch(error => { if (error?.code !== 'ERR_CANCELED' && error?.name !== 'CanceledError') setExistingUsers([]) }) }, 300); return () => { window.clearTimeout(timer); controller.abort() } }, [mode, existingQuery, form.condominiumId])
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); const input = { ...form, phoneNumber: form.phoneNumber.trim() || null, pixKeyType: form.pixKeyType || null, pixKey: form.pixKey.trim() || null, ...(mode === 'existing' && selectedExisting ? { existingUserId: selectedExisting.userId } : {}) }; if (mode === 'existing' && !selectedExisting) { setError('Selecione um usuário existente.'); return } try { if (editing) await updateSubManager(editing.id, input); else { const created = await createSubManager(input); if (created.temporaryPassword) setCredentials({ email: created.email, temporaryPassword: created.temporaryPassword }) }; closeForm(); await load() } catch (submitError) { setError(getErrorMessage(submitError)) } }
  const openPermissions = async (item: SubManager) => { setPermissionTarget(item); const rows = await listSubManagerPermissions(item.id); setPermissions(Object.fromEntries(rows.map(x => [x.module, x.allowed]))) }
  const pix = (item: SubManager) => item.pixKey ? `${item.pixKeyType === 'Phone' ? 'Telefone' : item.pixKeyType}: ${item.pixKey}` : 'Não informado'
  return <PageContainer maxWidth="none"><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ sm: 'center' }} gap={2}><Box><Typography variant="h1">Subsíndicos</Typography><Typography color="text.secondary">Cada usuário pode possuir apenas um vínculo ativo como subsíndico.</Typography></Box><Button variant="contained" onClick={() => { setEditing(null); setForm(emptyForm()); setOpen(true) }}>Novo subsíndico</Button></Stack>{error && <Alert severity="error" sx={{ mt: 2 }}>{error}</Alert>}
    <Paper variant="outlined" sx={{ mt: 3, overflowX: 'auto' }}><Table sx={{ width: '100%', minWidth: { xs: 1050, md: 0 }, tableLayout: 'fixed' }}><TableHead><TableRow><TableCell sx={{ width: '20%' }}>Nome</TableCell><TableCell sx={{ width: '18%' }}>Condomínio</TableCell><TableCell sx={{ width: '23%' }}>E-mail</TableCell><TableCell sx={{ width: '17%' }}>PIX</TableCell><TableCell sx={{ width: '10%' }}>Status</TableCell><TableCell sx={{ width: 280 }}>Ações</TableCell></TableRow></TableHead><TableBody>{items.map(item => <TableRow key={`${item.id}-${item.condominiumId}`}><TableCell>{item.fullName}</TableCell><TableCell>{item.condominiumName}</TableCell><TableCell>{item.email}</TableCell><TableCell>{pix(item)}</TableCell><TableCell>{item.isActive && item.hasActiveLink ? 'Ativo' : 'Inativo'}</TableCell><TableCell sx={{ whiteSpace: 'nowrap' }}><Button size="small" startIcon={<Edit />} onClick={() => openEdit(item)}>Editar</Button><Tooltip title="Gerenciar permissões"><Button size="small" startIcon={<AdminPanelSettings />} onClick={() => void openPermissions(item)}>Permissões</Button></Tooltip><IconButton aria-label={`Mais ações de ${item.fullName}`} onClick={event => setMenu({ item, anchor: event.currentTarget })}><MoreVert /></IconButton></TableCell></TableRow>)}</TableBody></Table></Paper>
    <Menu open={Boolean(menu)} anchorEl={menu?.anchor} onClose={() => setMenu(null)}>{menu && <><MenuItem onClick={() => { void resendSubManagerFirstAccess(menu.item); setMenu(null) }}><Send fontSize="small" sx={{ mr: 1 }} />Reenviar primeiro acesso</MenuItem><MenuItem onClick={() => { void resetSubManagerPassword(menu.item).then(result => setCredentials({ email: menu.item.email, temporaryPassword: result.temporaryPassword })); setMenu(null) }}><LockReset fontSize="small" sx={{ mr: 1 }} />Redefinir senha</MenuItem><MenuItem onClick={async () => { await setSubManagerStatus(menu.item.id, !menu.item.isActive); setMenu(null); await load() }}><Settings fontSize="small" sx={{ mr: 1 }} />{menu.item.isActive ? 'Inativar' : 'Ativar'}</MenuItem></>}</Menu>
    <Dialog open={open} onClose={closeForm} fullWidth maxWidth="sm"><Box component="form" onSubmit={event => void submit(event)}><DialogTitle>{editing ? 'Editar subsíndico' : 'Novo subsíndico'}</DialogTitle><DialogContent><Stack gap={2} pt={1}>{!editing && <Stack direction="row" gap={1}><Button variant={mode === 'new' ? 'contained' : 'outlined'} onClick={() => { setMode('new'); setSelectedExisting(null) }}>Nova pessoa</Button><Button variant={mode === 'existing' ? 'contained' : 'outlined'} onClick={() => setMode('existing')}>Usuário existente</Button></Stack>}{mode === 'existing' && !editing && <><Autocomplete options={existingUsers} value={selectedExisting} onChange={(_, value) => { setSelectedExisting(value); if (value) setForm({ ...form, fullName: value.fullName, email: value.email, phoneNumber: value.phoneNumber ?? '', pixKeyType: value.pixKeyType ?? '', pixKey: value.pixKey ?? '' }) }} getOptionLabel={value => `${value.fullName} — ${value.email}${value.unit ? ` • Unidade ${value.unit}` : ''}`} renderInput={params => <TextField {...params} label="Buscar por nome, e-mail ou telefone" value={existingQuery} onChange={e => setExistingQuery(e.target.value)} />} /><Alert severity="info">Este usuário já possui acesso ao Comvy. Será adicionado apenas o vínculo de subsíndico.</Alert></>}{mode === 'existing' && selectedExisting ? <Alert severity="info">Identidade preservada. Login, senha e PIX não serão alterados.</Alert> : <><TextField required label="Nome" value={form.fullName} onChange={e => setForm({ ...form, fullName: e.target.value })} /><TextField required type="email" label="E-mail" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /><TextField label="Telefone" value={form.phoneNumber} onChange={e => setForm({ ...form, phoneNumber: e.target.value })} /><PixFields type={form.pixKeyType} pixKey={form.pixKey} onTypeChange={value => setForm({ ...form, pixKeyType: value })} onKeyChange={value => setForm({ ...form, pixKey: value })} /></>}<TextField select required label="Condomínio" value={form.condominiumId} disabled={Boolean(editing)} onChange={e => setForm({ ...form, condominiumId: e.target.value })}>{condominiums.map(item => <MenuItem key={item.id} value={item.id}>{item.name}</MenuItem>)}</TextField></Stack></DialogContent><DialogActions><Button onClick={closeForm}>Cancelar</Button><Button type="submit" variant="contained">{editing ? 'Salvar' : 'Cadastrar'}</Button></DialogActions></Box></Dialog>
    <Dialog open={Boolean(permissionTarget)} onClose={() => setPermissionTarget(null)} fullWidth maxWidth="sm"><DialogTitle>Permissões de acesso</DialogTitle><DialogContent><Stack>{subManagerModules.map(module => <Stack key={module} direction="row" justifyContent="space-between" alignItems="center"><Typography>{labels[module]}</Typography><Button onClick={() => setPermissions(x => ({ ...x, [module]: !x[module] }))}>{permissions[module] ? 'Permitido' : 'Sem acesso'}</Button></Stack>)}</Stack></DialogContent><DialogActions><Button onClick={() => setPermissionTarget(null)}>Cancelar</Button><Button variant="contained" onClick={async () => { if (permissionTarget) await updateSubManagerPermissions(permissionTarget.id, subManagerModules.map(module => ({ module, allowed: permissions[module] ?? true }))); setPermissionTarget(null) }}>Salvar</Button></DialogActions></Dialog><Dialog open={Boolean(credentials)} onClose={() => setCredentials(null)}><DialogTitle>Credenciais temporárias</DialogTitle><DialogContent>{credentials && <Alert severity="warning">E-mail: {credentials.email}<br />Senha: {credentials.temporaryPassword}</Alert>}</DialogContent><DialogActions><Button onClick={() => setCredentials(null)}>Concluir</Button></DialogActions></Dialog>
  </PageContainer>
}
